/// Journal Entry Model
/// 
/// This represents a single journal entry in our database
/// Users can write about their thoughts, feelings, and experiences
class JournalEntry {
  // Unique ID for this entry (generated by Firestore)
  final String? id;
  
  // Which user this entry belongs to
  final String userId;
  
  // Title of the journal entry
  final String title;
  
  // The main content of the journal entry
  final String content;
  
  // Tags to categorize entries (e.g., 'gratitude', 'reflection')
  final List<String> tags;
  
  // When this entry was created
  final DateTime timestamp;
  
  // When this entry was last updated (for editing)
  final DateTime? updatedAt;

  /// Constructor - creates a new JournalEntry
  JournalEntry({
    this.id,
    required this.userId,
    required this.title,
    required this.content,
    this.tags = const [],
    required this.timestamp,
    this.updatedAt,
  });

  /// Convert JournalEntry to a Map (for saving to Firestore)
  Map<String, dynamic> toMap() {
    return {
      'userId': userId,
      'title': title,
      'content': content,
      'tags': tags, // Firestore can store lists directly
      'timestamp': timestamp.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(), // Nullable field
    };
  }

  /// Create a JournalEntry from a Map (for loading from Firestore)
  factory JournalEntry.fromMap(String id, Map<String, dynamic> map) {
    return JournalEntry(
      id: id,
      userId: map['userId'] ?? '',
      title: map['title'] ?? '',
      content: map['content'] ?? '',
      tags: List<String>.from(map['tags'] ?? []), // Convert list
      timestamp: DateTime.parse(map['timestamp']),
      updatedAt: map['updatedAt'] != null 
          ? DateTime.parse(map['updatedAt']) 
          : null,
    );
  }

  /// Create a copy of this JournalEntry with some fields changed
  JournalEntry copyWith({
    String? id,
    String? userId,
    String? title,
    String? content,
    List<String>? tags,
    DateTime? timestamp,
    DateTime? updatedAt,
  }) {
    return JournalEntry(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      title: title ?? this.title,
      content: content ?? this.content,
      tags: tags ?? this.tags,
      timestamp: timestamp ?? this.timestamp,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}

