/// Mood Entry Model
/// 
/// This represents a single mood tracking entry in our database
/// Each time a user logs their mood, we create one of these
class MoodEntry {
  // Unique ID for this entry (generated by Firestore)
  final String? id;
  
  // Which user this entry belongs to
  final String userId;
  
  // The mood value: 'great', 'good', 'okay', 'down', or 'struggling'
  final String mood;
  
  // Optional note the user can add
  final String? note;
  
  // When this mood was logged
  final DateTime timestamp;

  /// Constructor - creates a new MoodEntry
  MoodEntry({
    this.id,
    required this.userId,
    required this.mood,
    this.note,
    required this.timestamp,
  });

  /// Convert MoodEntry to a Map (for saving to Firestore)
  /// 
  /// Firestore stores data as key-value pairs (maps)
  /// This method converts our object into that format
  Map<String, dynamic> toMap() {
    return {
      'userId': userId,
      'mood': mood,
      'note': note ?? '', // Use empty string if note is null
      'timestamp': timestamp.toIso8601String(), // Convert date to string
    };
  }

  /// Create a MoodEntry from a Map (for loading from Firestore)
  /// 
  /// When we read data from Firestore, it comes as a map
  /// This method converts it back into a MoodEntry object
  factory MoodEntry.fromMap(String id, Map<String, dynamic> map) {
    return MoodEntry(
      id: id,
      userId: map['userId'] ?? '',
      mood: map['mood'] ?? '',
      note: map['note']?.toString().isEmpty == true ? null : map['note'],
      timestamp: DateTime.parse(map['timestamp']), // Convert string back to date
    );
  }

  /// Create a copy of this MoodEntry with some fields changed
  /// 
  /// Useful when updating an existing entry
  MoodEntry copyWith({
    String? id,
    String? userId,
    String? mood,
    String? note,
    DateTime? timestamp,
  }) {
    return MoodEntry(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      mood: mood ?? this.mood,
      note: note ?? this.note,
      timestamp: timestamp ?? this.timestamp,
    );
  }
}

