/// Reminder Model
/// 
/// This represents a wellness reminder that users can set
/// Reminders can be for journaling, mood check-ins, breathing exercises, etc.
class Reminder {
  // Unique ID for this reminder (generated by Firestore)
  final String? id;
  
  // Which user this reminder belongs to
  final String userId;
  
  // Type of reminder: 'Journal Entry', 'Mood Check-in', etc.
  final String type;
  
  // Custom message for the reminder (optional)
  final String? message;
  
  // Time of day to show the reminder (e.g., "09:00")
  final String time;
  
  // Whether this reminder is currently enabled
  final bool enabled;
  
  // When this reminder was created
  final DateTime createdAt;

  /// Constructor - creates a new Reminder
  Reminder({
    this.id,
    required this.userId,
    required this.type,
    this.message,
    required this.time,
    this.enabled = true,
    required this.createdAt,
  });

  /// Convert Reminder to a Map (for saving to Firestore)
  Map<String, dynamic> toMap() {
    return {
      'userId': userId,
      'type': type,
      'message': message ?? '',
      'time': time,
      'enabled': enabled,
      'createdAt': createdAt.toIso8601String(),
    };
  }

  /// Create a Reminder from a Map (for loading from Firestore)
  factory Reminder.fromMap(String id, Map<String, dynamic> map) {
    return Reminder(
      id: id,
      userId: map['userId'] ?? '',
      type: map['type'] ?? '',
      message: map['message']?.toString().isEmpty == true 
          ? null 
          : map['message'],
      time: map['time'] ?? '',
      enabled: map['enabled'] ?? true,
      createdAt: DateTime.parse(map['createdAt']),
    );
  }

  /// Create a copy of this Reminder with some fields changed
  Reminder copyWith({
    String? id,
    String? userId,
    String? type,
    String? message,
    String? time,
    bool? enabled,
    DateTime? createdAt,
  }) {
    return Reminder(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      type: type ?? this.type,
      message: message ?? this.message,
      time: time ?? this.time,
      enabled: enabled ?? this.enabled,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}

