// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFLMyz7u8EcRQMo72C48D1AAW481aP3VU',
    appId: '1:19904949934:web:8f2fb576d3bae224e9873f',
    messagingSenderId: '19904949934',
    projectId: 'mental-zen',
    authDomain: 'mental-zen.firebaseapp.com',
    storageBucket: 'mental-zen.firebasestorage.app',
    measurementId: 'G-JDESXXNRVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4AW6mSt0YVyU2tOgweS5EuW9Mk_IHI8M',
    appId: '1:19904949934:android:17a794e19856a0aee9873f',
    messagingSenderId: '19904949934',
    projectId: 'mental-zen',
    storageBucket: 'mental-zen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBol2LKLAStbaj4nSI7sSoNnxepPRveAjw',
    appId: '1:19904949934:ios:68890f9679b56539e9873f',
    messagingSenderId: '19904949934',
    projectId: 'mental-zen',
    storageBucket: 'mental-zen.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBol2LKLAStbaj4nSI7sSoNnxepPRveAjw',
    appId: '1:19904949934:ios:68890f9679b56539e9873f',
    messagingSenderId: '19904949934',
    projectId: 'mental-zen',
    storageBucket: 'mental-zen.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFLMyz7u8EcRQMo72C48D1AAW481aP3VU',
    appId: '1:19904949934:web:40156cb7b741f5dce9873f',
    messagingSenderId: '19904949934',
    projectId: 'mental-zen',
    authDomain: 'mental-zen.firebaseapp.com',
    storageBucket: 'mental-zen.firebasestorage.app',
    measurementId: 'G-L3VPN7VQP5',
  );
}
